title: 'Ikhan Choi'

url: '' 
baseurl: ''
archiveurl: '~/Git/mathnotes'

markdown: kramdown
markdown_ext: 'md'
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: nil

paginate: 5
paginate_path: '/pages/posts/page:num'

#disqus-id: your-disqus-id

source: .
destination: ./_site
gems: ['jekyll-paginate']


excerpt_separator: <!-- more -->