title: 'Ikhan Choi'

url: 'https://ikhanchoi.github.io'
baseurl: ''
archiveurl: 'C:/users/administrator/Desktop/Git/mathnotes'
#~/Git/mathnotes

markdown: kramdown
markdown_ext: 'md'
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1