title: 'Ikhan Choi'

url: 'https://ikhanchoi.github.io'
baseurl: ''

markdown: kramdown
markdown_ext: 'md'
highlighter: rouge

kramdown:
	input: GFM
	syntax_highlighter: rouge
	syntax_highlighter_opts:
		css_class: 'highlight'
		span:
			line_numbers: false
		block:
			line_numbers: true
			start_line: 1

google_analytics:
	tracking_id: G-BSE1ZPMKGC