title: 'Ikhan Choi'

url: 'https://ikhanchoi.github.io'
baseurl: ''
archiveurl: '~/Git/mathnotes'

markdown: kramdown
markdown_ext: 'md'
highlighter: rouge

kramdown:
  input: GFM
  math_engine: nil
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate: 5
paginate_path: '/pages/posts/page:num'

#disqus-id: your-disqus-id

source: .
destination: ./_site
gems: ['jekyll-paginate']


excerpt_separator: <!-- more -->
future: false