title: 'Ikhan Choi'

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: 'md'
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5
paginate_path: '/page_posts/page:num'

#disqus-id: your-disqus-id

source: .
destination: ./_site
gems: ['jekyll-paginate']


excerpt_separator: <!-- more -->